export const exampleCharacters = [
  {
    id: 1,
    name: 'Pikachu',
    image: '⚡',
    hp: 35,
    attack: 55,
    specialAttack: 50,
    defend: 40,
    specialDefend: 50,
    speed: 90,
  },
  {
    id: 2,
    name: 'Charizard',
    image: '🔥',
    hp: 78,
    attack: 84,
    specialAttack: 109,
    defend: 78,
    specialDefend: 85,
    speed: 100,
  },
  {
    id: 3,
    name: 'Blastoise',
    image: '💧',
    hp: 79,
    attack: 83,
    specialAttack: 85,
    defend: 100,
    specialDefend: 105,
    speed: 78,
  },
  {
    id: 4,
    name: 'Venusaur',
    image: '🌿',
    hp: 80,
    attack: 82,
    specialAttack: 100,
    defend: 83,
    specialDefend: 100,
    speed: 80,
  },
  {
    id: 5,
    name: 'Mewtwo',
    image: '🧬',
    hp: 106,
    attack: 110,
    specialAttack: 154,
    defend: 90,
    specialDefend: 90,
    speed: 130,
  },
  {
    id: 6,
    name: 'Alakazam',
    image: '🔮',
    hp: 55,
    attack: 50,
    specialAttack: 135,
    defend: 45,
    specialDefend: 95,
    speed: 120,
  },
];